// @Minionsart version
// credits  to  forkercat https://gist.github.com/junhaowww/fb6c030c17fe1e109a34f1c92571943f
// and  NedMakesGames https://gist.github.com/NedMakesGames/3e67fabe49e2e3363a657ef8a6a09838
// for the base setup for compute shaders
using System;
using UnityEngine;
using UnityEngine.Rendering;
using UnityEditor;

[ExecuteInEditMode]
public class GrassComputeScript : MonoBehaviour
{
    [Header("Components")]
    [SerializeField] private GrassPainter grassPainter = default;
    [SerializeField] private Mesh sourceMesh = default;
    [SerializeField] private Material material = default;
    [SerializeField] private ComputeShader computeShader = default;



    [Header("Grass")]
    [Range(1, 5)] public int allowedBladesPerVertex = 4;
    [Range(1, 5)] public int allowedSegmentsPerBlade = 5;

    // Blade
    [Header("Blade")]
    [Range(0, 1)] public float grassRandomHeight = 0.25f;
    [Range(0, 1)] public float bladeRadius = 0.2f;
    [Range(0, 1)] public float bladeForwardAmount = 0.38f;
    [Range(1, 5)] public float bladeCurveAmount = 2;

    [Range(0, 1)] public float bottomWidth = 0.1f;



    // Wind
    [Header("Wind")]
    public float windSpeed = 10;
    public float windStrength = 0.05f;
    // Interactor
    public float affectStrength = 1;
    // LOD
    [Header("LOD")]
    public float minFadeDistance = 40;
    public float maxFadeDistance = 60;
    public bool FadeInEditor;
    // Material
    [Header("Material")]
    public Color topTint = new Color(1, 1, 1);
    public Color bottomTint = new Color(0, 0, 1);
    // Other
    [Header("Other")]
    public UnityEngine.Rendering.ShadowCastingMode castShadow;


    private ShaderInteractor[] _interactors;

    private Camera _mainCamera;


    // The structure to send to the compute shader
    // This layout kind assures that the data is laid out sequentially
    [System.Runtime.InteropServices.StructLayout(System.Runtime.InteropServices.LayoutKind
        .Sequential)]
    private struct SourceVertex
    {
        public Vector3 position;
        public Vector3 normal;
        public Vector2 uv;
        public Vector3 color;
    }

    // A state variable to help keep track of whether compute buffers have been set up
    private bool _initialized;
    // A compute buffer to hold vertex data of the source mesh
    private ComputeBuffer _sourceVertBuffer;
    // A compute buffer to hold vertex data of the generated mesh
    private ComputeBuffer _drawBuffer;
    // A compute buffer to hold indirect draw arguments
    private ComputeBuffer _argsBuffer;
    // Instantiate the shaders so data belong to their unique compute buffers
    private ComputeShader _instantiatedComputeShader;
    [SerializeField] Material _instantiatedMaterial;
    // The id of the kernel in the grass compute shader
    private int _idGrassKernel;
    // The x dispatch size for the grass compute shader
    private int _dispatchSize;
    // The local bounds of the generated mesh
    private Bounds _localBounds;

    private Camera _sceneCam;

    // The size of one entry in the various compute buffers
    private const int SOURCE_VERT_STRIDE = sizeof(float) * (3 + 3 + 2 + 3);
    private const int DRAW_STRIDE = sizeof(float) * (3 + (3 + 2 + 3) * 3);
    private const int INDIRECT_ARGS_STRIDE = sizeof(int) * 4;

    private Bounds _bounds;

    // The data to reset the args buffer with every frame
    // 0: vertex count per draw instance. We will only use one instance
    // 1: instance count. One
    // 2: start vertex location if using a Graphics Buffer
    // 3: and start instance location if using a Graphics Buffer
    private readonly int[] _argsBufferReset = new int[] { 0, 1, 0, 0 };

#if UNITY_EDITOR
    private SceneView _view;


    // get the scene camera in case of no maincam
    public void OnFocus()
    {
        // Remove delegate listener if it has previously
        // been assigned.
        SceneView.duringSceneGui -= OnScene;
        // Add (or re-add) the delegate.
        SceneView.duringSceneGui += OnScene;
    }

    public void OnDestroy()
    {
        // When the window is destroyed, remove the delegate
        // so that it will no longer do any drawing.
        SceneView.duringSceneGui -= OnScene;
    }

    public void OnScene(SceneView scene)
    {
        _view = scene;

    }

#endif
    private void OnValidate()
    {
        // Set up components
        _mainCamera = Camera.main;
        grassPainter = GetComponent<GrassPainter>();
        sourceMesh = GetComponent<MeshFilter>().sharedMesh;  // generated by GeometryGrassPainter
    }



    private void OnEnable()
    {
        // If initialized, call on disable to clean things up
        if (_initialized)
        {
            OnDisable();
        }
#if UNITY_EDITOR
        SceneView.duringSceneGui += this.OnScene;
#endif
        _mainCamera = Camera.main;

        // Setup compute shader and material manually

        // Don't do anything if resources are not found,
        // or no vertex is put on the mesh.
        if (grassPainter == null || sourceMesh == null || computeShader == null || material == null)
        {
            return;
        }
        sourceMesh = GetComponent<MeshFilter>().sharedMesh;

        if (sourceMesh.vertexCount == 0)
        {
            return;

        }

        _initialized = true;

        // Instantiate the shaders so they can point to their own buffers
        _instantiatedComputeShader = Instantiate(computeShader);
        _instantiatedMaterial = Instantiate(material);

        // Grab data from the source mesh
        Vector3[] positions = sourceMesh.vertices;
        Vector3[] normals = sourceMesh.normals;
        Vector2[] uvs = sourceMesh.uv;
        Color[] colors = sourceMesh.colors;

        // Create the data to upload to the source vert buffer
        SourceVertex[] vertices = new SourceVertex[positions.Length];
        for (int i = 0; i < vertices.Length; i++)
        {
            Color color = colors[i];
            vertices[i] = new SourceVertex()
            {
                position = positions[i],
                normal = normals[i],
                uv = uvs[i],
                color = new Vector3(color.r, color.g, color.b) // Color --> Vector3
            };
        }

        int numSourceVertices = vertices.Length;

        // Each segment has two points
        int maxBladesPerVertex = Mathf.Max(1, allowedBladesPerVertex);
        int maxSegmentsPerBlade = Mathf.Max(1, allowedSegmentsPerBlade);
        int maxBladeTriangles = maxBladesPerVertex * ((maxSegmentsPerBlade - 1) * 2 + 1);

        // Create compute buffers
        // The stride is the size, in bytes, each object in the buffer takes up
        _sourceVertBuffer = new ComputeBuffer(vertices.Length, SOURCE_VERT_STRIDE,
            ComputeBufferType.Structured, ComputeBufferMode.Immutable);
        _sourceVertBuffer.SetData(vertices);

        _drawBuffer = new ComputeBuffer(numSourceVertices * maxBladeTriangles, DRAW_STRIDE,
            ComputeBufferType.Append);
        _drawBuffer.SetCounterValue(0);

        _argsBuffer =
            new ComputeBuffer(1, INDIRECT_ARGS_STRIDE, ComputeBufferType.IndirectArguments);

        // Cache the kernel IDs we will be dispatching
        _idGrassKernel = _instantiatedComputeShader.FindKernel("Main");

        // Set buffer data
        _instantiatedComputeShader.SetBuffer(_idGrassKernel, "_SourceVertices",
            _sourceVertBuffer);
        _instantiatedComputeShader.SetBuffer(_idGrassKernel, "_DrawTriangles", _drawBuffer);
        _instantiatedComputeShader.SetBuffer(_idGrassKernel, "_IndirectArgsBuffer",
            _argsBuffer);
        // Set vertex data
        _instantiatedComputeShader.SetInt("_NumSourceVertices", numSourceVertices);
        _instantiatedComputeShader.SetInt("_MaxBladesPerVertex", maxBladesPerVertex);
        _instantiatedComputeShader.SetInt("_MaxSegmentsPerBlade", maxSegmentsPerBlade);

        _instantiatedMaterial.SetBuffer("_DrawTriangles", _drawBuffer);



        // Calculate the number of threads to use. Get the thread size from the kernel
        // Then, divide the number of triangles by that size
        _instantiatedComputeShader.GetKernelThreadGroupSizes(_idGrassKernel,
            out uint threadGroupSize, out _, out _);
        _dispatchSize = Mathf.CeilToInt((float)numSourceVertices / threadGroupSize);

        // Get the bounds of the source mesh and then expand by the maximum blade width and height
        _localBounds = sourceMesh.bounds;
        _localBounds.Expand(Mathf.Max(2, 2));

        // Transform the bounds to world space
        _bounds = TransformBounds(_localBounds);

        SetGrassDataBase();
    }

    private void OnDisable()
    {
        // Dispose of buffers and copied shaders here
        if (_initialized)
        {
            // If the application is not in play mode, we have to call DestroyImmediate
            if (Application.isPlaying)
            {
                Destroy(_instantiatedComputeShader);
                //  Destroy(m_InstantiatedMaterial);
            }
            else
            {
                DestroyImmediate(_instantiatedComputeShader);
                // DestroyImmediate(m_InstantiatedMaterial);
            }

            // Release each buffer
            _sourceVertBuffer?.Release();
            _drawBuffer?.Release();
            _argsBuffer?.Release();
        }

        _initialized = false;
    }

    // LateUpdate is called after all Update calls
    private void LateUpdate()
    {
        // If in edit mode, we need to update the shaders each Update to make sure settings changes are applied
        // Don't worry, in edit mode, Update isn't called each frame
        if (Application.isPlaying == false)
        {
            OnDisable();
            OnEnable();
        }

        // If not initialized, do nothing (creating zero-length buffer will crash)
        if (!_initialized)
        {
            // Initialization is not done, please check if there are null components
            // or just because there is not vertex being painted.
            return;
        }

        // Clear the draw and indirect args buffers of last frame's data
        _drawBuffer.SetCounterValue(0);
        _argsBuffer.SetData(_argsBufferReset);



        // Update the shader with frame specific data
        SetGrassDataUpdate();

        // Dispatch the grass shader. It will run on the GPU
        _instantiatedComputeShader.Dispatch(_idGrassKernel, _dispatchSize, 1, 1);

        // DrawProceduralIndirect queues a draw call up for our generated mesh
        Graphics.DrawProceduralIndirect(_instantiatedMaterial, _bounds, MeshTopology.Triangles,
            _argsBuffer, 0, null, null, castShadow, true, gameObject.layer);
    }


    private void SetGrassDataBase()
    {

        _interactors = (ShaderInteractor[])FindObjectsOfType(typeof(ShaderInteractor));
        
        // Send things to compute shader that dont need to be set every frame
        _instantiatedComputeShader.SetMatrix("_LocalToWorld", transform.localToWorldMatrix);
        _instantiatedComputeShader.SetFloat("_Time", Time.time);

        _instantiatedComputeShader.SetFloat("_GrassRandomHeight", grassRandomHeight);

        _instantiatedComputeShader.SetFloat("_WindSpeed", windSpeed);
        _instantiatedComputeShader.SetFloat("_WindStrength", windStrength);

        _instantiatedComputeShader.SetFloat("_InteractorStrength", affectStrength);

        _instantiatedComputeShader.SetFloat("_BladeRadius", bladeRadius);
        _instantiatedComputeShader.SetFloat("_BladeForward", bladeForwardAmount);
        _instantiatedComputeShader.SetFloat("_BladeCurve", Mathf.Max(0, bladeCurveAmount));
        _instantiatedComputeShader.SetFloat("_BottomWidth", bottomWidth);

        if (FadeInEditor || Application.isPlaying == true)
        {


            _instantiatedComputeShader.SetFloat("_MinFadeDist", minFadeDistance);
            _instantiatedComputeShader.SetFloat("_MaxFadeDist", maxFadeDistance);
        }
        else
        {
            _instantiatedComputeShader.SetFloat("_MinFadeDist", 0);
            _instantiatedComputeShader.SetFloat("_MaxFadeDist", 999);
        }



        _instantiatedComputeShader.SetFloat("_OrthographicCamSize", Shader.GetGlobalFloat("_OrthographicCamSize"));
        _instantiatedComputeShader.SetVector("_OrthographicCamPos", Shader.GetGlobalVector("_OrthographicCamPos"));

        _instantiatedMaterial.SetColor("_TopTint", topTint);
        _instantiatedMaterial.SetColor("_BottomTint", bottomTint);

    }

    private void SetGrassDataUpdate()
    {
        // Compute Shader
        //  m_InstantiatedComputeShader.SetMatrix("_LocalToWorld", transform.localToWorldMatrix);
        _instantiatedComputeShader.SetFloat("_Time", Time.time);

        if (_interactors.Length > 0)
        {
            Vector4[] positions = new Vector4[_interactors.Length];
            for (int i = 0; i < _interactors.Length; i++)
            {
                positions[i] = _interactors[i].transform.position;
 				positions[i].w = _interactors[i].radius;

            }
            int shaderID = Shader.PropertyToID("_PositionsMoving");
            _instantiatedComputeShader.SetVectorArray(shaderID, positions);
            _instantiatedComputeShader.SetFloat("_InteractorsLength", _interactors.Length);
        }
        // else
        // {
        //     m_InstantiatedComputeShader.SetVector("_PositionMoving", Vector3.zero);
        // }

        if (_mainCamera != null)
        {
            _instantiatedComputeShader.SetVector("_CameraPositionWS", _mainCamera.transform.position);

        }
#if UNITY_EDITOR
        // if we dont have a main camera (it gets added during gameplay), use the scene camera
        else if (_view != null)
        {
            _instantiatedComputeShader.SetVector("_CameraPositionWS", _view.camera.transform.position);
        }
#endif

    }


    // This applies the game object's transform to the local bounds
    // Code by benblo from https://answers.unity.com/questions/361275/cant-convert-bounds-from-world-coordinates-to-loca.html
    private Bounds TransformBounds(Bounds boundsOS)
    {
        var center = transform.TransformPoint(boundsOS.center);

        // transform the local extents' axes
        var extents = boundsOS.extents;
        var axisX = transform.TransformVector(extents.x, 0, 0);
        var axisY = transform.TransformVector(0, extents.y, 0);
        var axisZ = transform.TransformVector(0, 0, extents.z);

        // sum their absolute value to get the world extents
        extents.x = Mathf.Abs(axisX.x) + Mathf.Abs(axisY.x) + Mathf.Abs(axisZ.x);
        extents.y = Mathf.Abs(axisX.y) + Mathf.Abs(axisY.y) + Mathf.Abs(axisZ.y);
        extents.z = Mathf.Abs(axisX.z) + Mathf.Abs(axisY.z) + Mathf.Abs(axisZ.z);

        return new Bounds { center = center, extents = extents };
    }
}
